apiVersion: v1
kind: ConfigMap
metadata:
  name: opendatahub-mcplifecycleoperator-config
  namespace: mcp-lifecycle-module-operator-system
data:
  operand-image: "quay.io/redhat-user-workloads/mcp-lifecycle-operator-tenant/mcp-lifecycle-operator-main@sha256:b5e1f2fd3b34ba30787a809fa8bf43a56a668ea771057d387e1ccd3008a4294c"
  operand-namespace: "mcp-lifecycle-operator-system"
